
city-weather:
  scheduler:
    cron: 0 * * ? * *
  cities:
    - code: 2147714
      name: Sydney
    - code: 7839805
      name: Melbourne
    - code: 7839791
      name: Wollongong
  provider:
    open:
      url: https://api.openweathermap.org/data/2.5/weather
      appid: a80db045e474210a3cf0720934733ae0
      parameters:
        units:
          - metric